name: Deployment Workflow
on:
    push:
        branches: [deploy]

jobs:
    job_one:
        name: Check Status, Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Testing SSH connection with server.
              uses: appleboy/ssh-action@master
              with:
                host: 143.198.229.142
                username: root
                key: ${{secrets.DIGITALOCEAN_SECRET}}
                port: 22
                script: |
                    cd deploy
                    git checkout deploy
                    git status
            - name: Pull Changes from main.
              uses: appleboy/ssh-action@master
              with:
                host: 143.198.229.142
                username: root
                key: ${{secrets.DIGITALOCEAN_SECRET}}
                port: 22
                script: |
                    cd deploy
                    git checkout deploy
                    git pull origin main
                    git status
            - name: Build and Deploy Changes
              uses: appleboy/ssh-action@master
              with:
                host: 143.198.229.142
                username: root
                key: ${{secrets.DIGITALOCEAN_SECRET}}
                port: 22
                script: |
                    cd deploy
                    git checkout deploy
                    yarn install
                    cd backend
                    yarn install
                    cd ../
                    yarn build
